# see docs in https://github.com/openai/codex/blob/main/docs/config.md

model = "gpt-5.2-codex"
model_reasoning_effort = "high"
# notify = ["/home/isymchych/.codex/notify.sh"]
network_access = true
sandbox_mode = "workspace-write"

[features]
web_search_request = true
unified_exec = true
apply_patch_freeform = true
skills = true
shell_snapshot = true

[tui]
notifications = true

[projects."/home/isymchych/dotfiles"]
trust_level = "trusted"

[projects."/home/isymchych/work"]
trust_level = "trusted"

[projects."/home/isymchych/projects"]
trust_level = "trusted"
