[[input.prepend_keymap]]
  on   = [ "<Esc>" ]
  run  = "close"
  desc = "Cancel input"

[[mgr.prepend_keymap]]
  on   = [ "l" ]
  run  = "plugin smart-enter"
  desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
  on   = [ "<Enter>" ]
  run  = "plugin smart-enter"
  desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
  on = [ "T" ]
  run = "plugin hide-preview"
  desc = "Toggle preview pane"

[[mgr.prepend_keymap]]
  on = [ "g", "m" ]
  run = "cd \"/run/media/$USER\""
  desc = "Go to mounted media"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# use dragon-drop to create drag-n-drop are with selected files
[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon -x -i -T "$0"'
