[mgr]
sort_by = "natural"
sort_dir_first = true
ratio = [2, 4, 2]

[opener]
imv = [
  { run = 'imv-dir "$@"', desc = "Open image in imv-dir", orphan = true, for = "linux" },
]
mpv = [
  { run = 'mpv "$@"', desc = "Open video in mpv", orphan = true, for = "linux" },
]
emacs = [
  { run = 'emacs "$@"', desc = 'Open in Emacs GUI', orphan = true }
]

[open]
prepend_rules = [
  { mime = "image/*", use = ["imv", "image"] },
  { mime = "video/*", use = "mpv" },
  { mime = "text/*", use = "emacs" },
]
